source_code/source_code/source_code/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('woke/', include('woke.urls')),
]

source_code/source_code/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('woke/', include('woke.urls')),
]

source_code/woke/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^welcome$',views.welcome),
    url(r'^login$',views.login),
    url(r'^successful$',views.successful),
    url(r'^signup$',views.signup),
    url(r'^explore/([^/]+)/',views.explore_email),
    url(r'^explore$',views.explore),
    url(r'^wallet$',views.wallet),
    url(r'^uprofile/([^/]+)/',views.uprofile_email),
    url(r'^uprofile$',views.uprofile),
    url(r'^cprofile$',views.cprofile),
    url(r'^cprofile/([^/]+)/([^/]+)/$',views.cprofile_email),
    url(r'^settings$',views.settings),
    url(r'^homefeed$',views.homefeed),
    url(r'^homefeed/$',views.homefeed),
    url(r'^homefeed/([^/]+)/([^/]+)/',views.homefeed_email),
    url(r'^gotohomefeed/([^/]+)/$',views.gotohomefeed),
    url(r'^nextpage/([^/]+)/([^/]+)/',views.nextpage),
    url(r'^topaypal/([^/]+)/([^/]+)/$',views.topaypal_email),
    url(r'^topaypal$',views.topaypal),
    url(r'^canc_donate$',views.canc_donate),
    url(r'^topaypal/([^/]+)/([^/]+)/([^/]+)/$',views.canc_donate_email),
    url(r'^suc_donate$',views.suc_donate),
    url(r'^upload$',views.upload),
    url(r'^search$',views.search),
    url(r'^search/([^/]+)/$',views.search_email),
    url(r'^comment$',views.comment),
    url(r'^comment/([^/]+)/([^/]+)/$',views.comment_email),
    url(r'^profile/([^/]+)/$',views.profile),
    url(r'^post/([^/]+)/$',views.add_post),
]

source_code/woke/views.py
from django.shortcuts import render, redirect
from django import forms
#from django.contrib import auth
#from django.contrib.auth.models import User 
from django.db.models import Q
from django.contrib.auth.hashers import make_password, check_password
from .models import *
import re
class UserForm(forms.Form):
    username = forms.CharField(label='username',max_length=100)
    email = forms.CharField(label='email',max_length=100)
    password = forms.CharField(label='password',max_length=100,widget=forms.PasswordInput())
    confirmed_password = forms.CharField(label='confirmed_password',max_length=100,widget=forms.PasswordInput())

class EmailForm(forms.Form):
    email = forms.CharField(label='email',max_length=100)
    
def welcome(request):
    return render(request,'welcome.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)
        try:
            a = User.objects.get(email=username)
        except User.DoesNotExist:
            return render(request,'login.html',{'login_error':'incorrect email'})
        if check_password(password, a.password):
            return redirect('/woke/homefeed/'+str(a.email)+'/'+str(find_next(0)))
        else:
            return render(request,'login.html',{'login_error':'incorrect password'})
        #return render(request,'explore.html',{'user_email':a.email})
        
    return render(request,'login.html')

def successful(request):
    return render(request,'successful.html')

def signup(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            email = uf.cleaned_data['email']
            password = uf.cleaned_data['password']
            confirmed_password = uf.cleaned_data['confirmed_password']
            if password != confirmed_password:
                return render(request,'signup.html',{'signup_error':'Not the same password!'})
            str=r'^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){0,4}@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){0,4}$'
            if not re.match(str,email):
                return render(request,'signup.html',{'signup_error':'invalid email'})
            
            try:
                User.objects.get(email=email)
            except User.DoesNotExist:
                encrypted_password = make_password(password)
                user = User(email=email,username=username,password=encrypted_password)
                user.save()
                try:
                    a = User.objects.get(email=email)
                except User.DoesNotExist:
                    return render(request,'signup.html',{'signup_error':'try again please'})
                common = Common(user_id=a.id,text='Hi, everyone!')
                common.save()
                return render(request,'successful.html')
            return render(request,'signup.html',{'signup_error':'email already exists'})
            
    else:
        uf = UserForm()
    return render(request,'signup.html')

def explore(request):
    return render(request,'explore.html')

def explore_email(request,email):
    a = Post.objects.filter()
    if len(a) > 5:
        size = 5
    else:
        size = len(a)
    results=[]
    for i in range(size):
        results.append('/'+a[i].picture.url)
    content={'user_email' : email,'pictures':results}
    return render(request,'explore.html', content)

def uprofile_email(request, email):
    try:
        a = User.objects.get(email=email)
    except User.DoesNotExist:
        return render(request,'uprofile.html')
    try:
        b = Common.objects.get(user_id=a.id)
    except User.DoesNotExist:
        return render(request,'uprofile.html')
    
    if request.method=='POST':
        print('WOW!')
        profile_photo = request.FILES.get('file')
        b.photo = profile_photo
        b.save()
        
    content = {
            'user_email' : email,
            'name' : a.username,
            'text' : b.text,
            'photo' : '/'+b.photo.url,
        }
    
    return render(request,'uprofile.html',content)

def uprofile(request):
    return render(request,'uprofile.html')

def add_post(request,email):
    try:
        a = User.objects.get(email=email)
    except User.DoesNotExist:
        return render(request,'welcome.html')
    if request.method=='POST':
        print('wow')
        text = request.POST.get('text')
        if text != None:
            post = Post(
                user_id = a.id,
                text = text,
                picture = request.FILES.get('file'),
            )
            post.save()
        return redirect('/woke/cprofile/'+email+'/'+email)
    return render(request,'post.html',{'email':email})

def cprofile(request):
    return render(request,'cprofile.html')

def wallet(request):
    return render(request,'wallet.html')

def settings(request):
    return render(request,'settings.html')

def topaypal(request):
    return render(request, "topaypal.html")

def topaypal_email(request,email,number):
    return render(request, "topaypal.html",{'email':email})

def canc_donate(request):
    return render(request, "canc_donate.html")

def canc_donate_email(request,a,b,c):
    if c == 'canc_donate':
        return render(request, "canc_donate.html", {'url':a+'/'+b})
    else:
        return render(request, "suc_donate.html", {'url':a+'/'+b})

def suc_donate(request):
    return render(request, "suc_donate.html")

def homefeed(request):
    return render(request, "homefeed.html")

def homefeed_email(request,email,number):
    try:
        b = Post.objects.get(id=number)
    except User.DoesNotExist:
        print("Goo")
        return render(request, "homefeed.html")
    print("Good")
    print(b.picture.url)
    try:
        c = Charity.objects.get(user_id=b.user_id)
    except User.DoesNotExist:
        print('bala')
    try:
        d = User.objects.get(id=b.user_id)
    except User.DoesNotExist:
        print('bala')
    content = {
            'post_text':b.text,
            'picture':'/'+str(b.picture.url),
            'logo':'/'+str(c.logo.url),
            'number':number,
            'user_email':email,
            'charity_email':d.email,
        }
    return render(request, "homefeed.html",content)

def upload(request):
    
    if request.method == 'POST':
        post = Post(
            user_id=14,
            picture=request.FILES.get('file'),
            text='bala'
        )
        post.save()
    
    return render(request, 'uploading.html')

def find_next(number):
    number = number + 1
    Bool = True
    while Bool:
        Bool = False
        try:
            a = Post.objects.get(id=number)
        except:
            number = number + 1
            if number > 100:
                number = 0
            Bool = True
    return number

def nextpage(request,email,number):
    return homefeed_email(request,email,str(find_next(int(number))))

def cprofile_email(request,charity_email,user_email):
    try:
        a = User.objects.get(email=charity_email)
    except User.DoesNotExist:
        return render(request,'cprofile.html')
    try:
        b = Charity.objects.get(user_id=a.id)
    except User.DoesNotExist:
        return render(request,'cprofile.html')
    c = Post.objects.filter(user_id=a.id)
    if len(c) > 5:
        size = 5
    else:
        size = len(c)
    results=[]
    for i in range(size):
        results.append('/'+c[i].picture.url)
    content = {
            'user_name' : a.username,
            'user_email' : user_email,
            'logo' : '/'+b.logo.url,
            'text' : b.text,
            'pictures':results,
        }
    if user_email == charity_email:
        content['button'] = 'yes'
    else:
        content['button'] = ''
    return render(request,'cprofile.html',content)

def search(request):
    if request.method == 'POST':
        a = request.POST.get('searchname')
        try:
            b = User.objects.filter(email=a)
        except User.DoesNotExist:
            return render(request,'search.html',{'search_result':'No results.'})
        
        return render(request,'search.html',{'search_result':b.email})
    return render(request, 'search.html')

def search_email(request, email):
    content = {
                'ownemail' : email,
                'post_id' : str(find_next(0)),
            }
    if request.method == 'POST':
        a = request.POST.get('searchname')
        b = User.objects.filter(Q(username__contains=a) | Q(email__contains=a))
        if len(b)==0:
            content['search_result']='No results'
            return render(request,'search.html',content)
        results=[]
        for i in range(len(b)):
            results.append(str(b[i]))
            
        content['results'] = results
        return render(request,'search.html',content)
    return render(request,'search.html',content)

def comment(request):
    comments=['bala','boom','Greetings!']
    return render(request, 'comment.html',{'comments':comments})

def comment_email(request,email,post_id):
    
    try:
        a = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        return render(request, 'comment.html')
    try:
        b = Charity.objects.get(user_id=a.user_id)
    except Charity.DoesNotExist:
        return render(request, 'comment.html')
    
    if request.method == 'POST':
        comment_text = request.POST.get('comment_text')
        comment = Comment(
                post_id = post_id,
                user_email = email,
                text = comment_text,
        )
        comment.save()
    
    comments = []

source_code/templates/canc_donate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, user-scalable=0, minimal-ui">
    <title>PaymentCancelled</title>
<style>
	#warning {
			width:100px;
			height:100px;
			position:relative;
	}
	#wword {
			top: 75px;
			left: 25px;
			width:700px;
			height:700px;
			position:relative;
			font-size:150%;
			text-align:left; 
			color:#ababc7; 
			font-weight:bold;
	}
	.w {
			position:absolute;
			left:140px;
			top:5px;	
		}
	.b {
			position:absolute;
			width:30px;
			height:30px;
			left:0px;
			top:0px;	
	}
</style>
</head>


<body>

<div id= "warning">
<a href = "/woke/homefeed/{{ url }}"><img src ="/static/back.png" class = "b"></a>
<!--<img src ="/static/w-logo.png" class = "w">-->
<div>

<div id= "wword">
<p>Payment has been cancelled.</p>
<div>
</body>


</html>

source_code/templates/comment.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script type="text/javascript">
        var cssEl = document.createElement('style');
                      document.documentElement.firstElementChild.appendChild(cssEl);

        function setPxPerRem(){
            var dpr = 1;
            var pxPerRem = document.documentElement.clientWidth * dpr / 10;
            cssEl.innerHTML = 'html{font-size:' + pxPerRem + 'px!important;}';
        }
        setPxPerRem();
    </script>
</head>
<style>
	*{
		margin:0;
		padding: 0;
	}
	body{
		overflow:scroll;
	}
	#text-A{
		position: fixed;
		bottom: 0.5rem;
		height:0.8rem;
		width:6rem;
		left:1rem;
		border-radius: 0.2rem;

		

	}
	#commentbtn{
	position:fixed;
	right:0.8rem;
	bottom:0.5rem;

	}

	#commentArea{
		width: 9.8rem;
		height: 9rem;
		overflow-y:auto;
		border-radius: 0.2rem;
		border: 2px outset #d6d4d4;
		margin:0 auto;


	}
	#logo_img{
		border-radius: 3rem;
		width: 1.5rem;
		height: 1.5rem;
		margin-left:0.3rem;
		margin-top:0.5rem;

	}

	.back_img{
	width:1rem;
	height:1rem;
	margin-top:0.2rem;
	}

	.Woke_img{
	position:fixed;
	left:3rem;
	width:4rem;
	height:1.5rem;
	opacity:0.5;
	}

.glyphicon{

  color:black;
  font-size:0.6rem;
  margin-left:0.32rem;
  margin-right:0.31rem;

 }
 
 .nav{

  background-color:#d6d4d4;
  width:10rem;


 }
 
 
 .set{

padding-top:1.2rem;

}


</style>
<body>
<div class="set">
<ul class="nav nav-pills navbar-fixed-top">
  <li role="presentation" ><a href="/woke/homefeed/{{ email }}/{{ post_id }}"><i class="glyphicon glyphicon-chevron-left"></i></a></li>
  <li role="presentation" ><i class="glyphicon aa"></i></li>
</ul>

<div id="top-lane" style="vertical-align: middle;">
    <img id="logo_img" src="/{{ chogo }}" alt="logo"><span style="font-size: 0.4rem;">{{ text }}</span>
    </br>
    </br>

</div>
<div id="commentArea">
    <li>{{ result }}</li>
    {% for comment in comments %}
        <li>{{ comment }}</li>
    {% endfor %}
    </body>
    <!--<ul id="ullist"></ul>-->
</div>
<div id="postArea">

    <form method="POST">
        <input type="text" id="text-A" name="comment_text" placeholder="Add a comment.">
        <input id="commentbtn" class="btn btn-default" type="submit" value="Send">
    </form>
</div>
</div>
<script>








</script>
</body>
</html>



</script>
</body>
</html>

source_code/templates/cprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>Title</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <script type="text/javascript">
        var cssEl = document.createElement('style');
                      document.documentElement.firstElementChild.appendChild(cssEl);

        function setPxPerRem(){
            var dpr = 1;
            var pxPerRem = document.documentElement.clientWidth * dpr / 10;
            cssEl.innerHTML = 'html{font-size:' + pxPerRem + 'px!important;}';
        }
        setPxPerRem();
    </script>
    
<style>

*{padding:0;margin:0;}


  .scrolling-wrapper {
  
    overflow-y: hidden;
    white-space: nowrap;

  }



  .card {
    display: inline-block;
  }


.main{

position:absolute;
position:fixed;
top:1.5rem;


}

.img{
width:2.5rem;
height:2.5rem;}

.glyphicon{

  color:black;
  font-size:0.6rem;
  margin-left:0.32rem;
  margin-right:0.31rem;

 }
 
 .nav{

  background-color:#d6d4d4;
  width:10rem;


 }
 



.logo{
 z-index:999}
 
#logo_img{
		border-radius: 3rem;
		width: 1.6rem;
		height: 1.6rem;
		margin-left:0.3rem;


	}
	
body{
overflow:hidden;}

span{
font-size:0.5rem;}

p{
font-size:0.4rem;
margin:0.4rem;}

.aa{
width:5.3rem;
}
</style>

</head>


<BODY>

</br>
</br>
</br>
</br>

<ul class="nav nav-pills navbar-fixed-top">
  <li role="presentation" ><i class="glyphicon glyphicon-chevron-left"></i></li>
  <li role="presentation" ><i class="glyphicon aa"></i></li>
  {% if button == 'yes' %}<li role="presentation"><a href="/woke/post/{{ user_email }}"><i class="glyphicon glyphicon-plus post"></i></a></li>{% endif %}
</ul>

<div>
<img id="logo_img" src={{ logo }}>&nbsp;&nbsp;<span>{{ user_name }}</span><i class="glyphicon glyphicon-leaf"></i>
<button type="button" class="btn btn-default">Support</button>
<div>

<p>{{ text }}</p>

<p style="font-size:0.4rem;text-align:center; color:#d6d4d4; font-weight:bold; ">Category</p>
<div class="scrolling-wrapper" >
{% for picture in pictures %}
       <div class="card"><img class="img" src={{ picture }} alt="test"></div>
    {% endfor %}
</div>




<ul class="nav nav-pills navbar-fixed-bottom">
  <li role="presentation" ><a href="/woke/gotohomefeed/{{ user_email }}"><i class="glyphicon glyphicon-home"></i></a></li>
  <li role="presentation"><a href="/woke/search/{{ user_email }}"><i class="glyphicon glyphicon-search"></i></a></li>
  <li role="presentation"><a href="/woke/explore/{{ user_email }}"><i class="glyphicon glyphicon glyphicon-cloud"></i></a></li>
	  <li role="presentation"><a href="/woke/support/{{ user_email }}"><i class="glyphicon glyphicon-list"></i></a></li>
  <li role="presentation"><a href="/woke/uprofile/{{ user_email }}"><i class="glyphicon glyphicon-user"></i></a></li>
</ul>
</BODY>

</html>

source_code/templates/homefeed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>Homefeed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <script type="text/javascript">
        var cssEl = document.createElement('style');
                      document.documentElement.firstElementChild.appendChild(cssEl);

        function setPxPerRem(){
            var dpr = 1;
            var pxPerRem = document.documentElement.clientWidth * dpr / 10;
            cssEl.innerHTML = 'html{font-size:' + pxPerRem + 'px!important;}';
        }
        setPxPerRem();
    </script>
    
<style>

*{padding:0;margin:0;}




.glyphicon{
  color:black;
  font-size:0.6rem;
  margin-left:0.32rem;
  margin-right:0.31rem;

 }
 
 .nav{

  background-color:#d6d4d4;
  width:10rem;


 }
 

#logo_img{
		border-radius: 0.5rem;
		width: 1.0rem;
		height: 0.8rem;
		margin:0.5rem 0 0 0.3rem;

	}


	

.aa{
width:5.3rem;
}



.new{
margin:0;
padding:0;
font-size:0.7rem;}

.middle{
background-color:white;}

p{
font-size:0.4rem;
margin: 0 0.4rem;}

.btn{


margin-top:0.3rem;
margin-left:7.5rem;



}

.set{

padding-bottom:1.5rem;

}



#chogo{
position:absolute;
z-index: 999;
top: 3rem;
right:0.5rem;
border-radius: 0.5rem;
width: 1.0rem;
height: 0.8rem;

}

#home_img{
width:10rem;
height:10rem;
margin:0.2rem 0;
}



</style>

</head>


<body>

</br>
</br>
<div class="set" >

<ul class="nav nav-pills navbar-fixed-top">
  <li role="presentation" ><i class="glyphicon glyphicon-envelope"></i></li>
  <li role="presentation" ><i class="glyphicon aa"></i></li>
  <li role="presentation"><i class="glyphicon glyphicon-cog"></i></li>
</ul>


<img id="logo_img" src={{ logo }} onclick="location='/woke/cprofile/{{ charity_email }}/{{ user_email }}'">




<img id="home_img" src={{ picture }}>
<img id="chogo" src={{ logo }} onclick="location='/woke/cprofile/{{ charity_email }}/{{ user_email }}'">          


<ul class="nav middle nav-pills">
  <li role="presentation" ><a href="/woke/topaypal/{{ user_email }}/{{ number }}"><i class="glyphicon glyphicon-usd new"></i></a></li>
  <li role="presentation"><a href="/woke/comment/{{ user_email }}/{{ number }}"><i class="glyphicon glyphicon-comment new"></i></a></li>
</ul>

<p>{{ post_text }}</p>
<button type="button" class="btn btn-default" onclick="location='/woke/nextpage/{{ user_email }}/{{ number }}'">Next Page</button>

</div>
<ul class="nav nav-pills navbar-fixed-bottom">
  <li role="presentation" ><i class="glyphicon glyphicon-home"></i></li>
  <li role="presentation"><a href="/woke/search/{{ user_email }}"><i class="glyphicon glyphicon-search"></i></a></li>
  <li role="presentation"><a href="/woke/explore/{{ user_email }}"><i class="glyphicon glyphicon glyphicon-cloud"></i></a></li>
  <li role="presentation"><a href="#"><i class="glyphicon glyphicon-list"></i></a></li>
  <li role="presentation"><a href="/woke/profile/{{ user_email }}"><i class="glyphicon glyphicon-user"></i></a></li>
</ul>
</body>

</html>

source_code/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
<title>Title</title>
      <script type="text/javascript">
        var cssEl = document.createElement('style');
                      document.documentElement.firstElementChild.appendChild(cssEl);

        function setPxPerRem(){
            var dpr = 1;
            var pxPerRem = document.documentElement.clientWidth * dpr / 10;
            cssEl.innerHTML = 'html{font-size:' + pxPerRem + 'px!important;}';
        }
        setPxPerRem();
    </script>
</head>

<style>

*{
margin:0;
padding:0;}

#background {
    background-image:url("/static/background.png");
    background-repeat: no-repeat;
    width:10rem;
    height:16rem;
    opacity:0.6;
    
}


input{
  position: fixed;
  left: 1.75rem;
  border: none 0;
  outline: medium;
  background: transparent;
  border-bottom: 1px solid #E8E8E8;
  display:block;
  width:6.5rem;
  margin-bottom: 2rem;
 
}
button {
  position: absolute;
  left: 1.75rem;
  top:4rem;
  border-radius: 0.2rem;
  background-color: white;
  border: none;
  color: #686464;
  text-align: center;
  display: inline-block;
  font-size: 0.4rem;
  width: 6.5rem;
  height:0.8rem;
}
input::placeholder{
  font-size: 0.4rem;
}
form{
    position: absolute;
    top: 6.5rem;
  }
  
hr{
  color: #686464;
}
#info{
align:center;
position:fixed;
top:4.5rem;
color: white;
font-size:0.5rem;
}


</style>
<body>
   <div id="background"></div>
   <p id="info">{{ login_error }}</p >
<form action="/woke/login" method="POST">
    <input placeholder="User name/Email" type="text"id="username"name="username"/></br>
    <input placeholder="Password" type="password"id="password"name="password"/>
    <button type="submit">Log in</button>
</form>
</body>
</html>

source_code/templates/navigator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<style>
  .navbar {
    overflow: hidden;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
</style>

<body>
<div class="navbar">
  <a href="#home" class="active"><img src="home.png" alt="home" width="80" height="80"></a>
  <a href="explore.html" class="active"><img src="earth.png" alt="home" width="73" height="73"></a>
  <a href="#home" class="active"><img src="search.png" alt="home" width="73" height="73"></a>
  <a href="#home" class="active"><img src="list.png" alt="home" width="73" height="73"></a>
  <a href="#home" class="active"><img src="profile.png" alt="home" width="73" height="73"></a>
</div>


</body>
</html>

source_code/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>Sign up page</title>
    <script type="text/javascript">
        var cssEl = document.createElement('style');
        document.documentElement.firstElementChild.appendChild(cssEl);

        function setPxPerRem(){
            var dpr = 1;
            var pxPerRem = document.documentElement.clientWidth * dpr / 10;
            cssEl.innerHTML = 'html{font-size:' + pxPerRem + 'px!important;}';
        }
        setPxPerRem();
    </script>
</head>
<style>

    *
    {padding:0; margin:0;}
    
    #background {
        background-image:url("/static/background.png");
        background-repeat: no-repeat;
        width:10rem;
        height:16rem;
        opacity:0.6;
        overflow: hidden;

    }
    
    body{
        overflow: hidden;
    }

    img{
        position: absolute;
        top: 180px;
        left: 80px;
    }
    
    button{
        position: fixed;
        left: 1.5rem;
        top:10rem;
        border-radius: 0.2rem;
        background-color:white;
        color: #989898;
        text-align: center;
        display: inline-block;
        font-size: 0.5rem;
        width: 7rem;
        height:0.8rem;
        opacity:0.8;
    }
    
    input{
        left: 85px;
        top: 300px;
        border: none 0;
        outline: medium;
        background: transparent;
        -webkit-appearance: none;
        -moz-appearance: none;
        -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
        -moz-tap-highlight-color: transparent;
        border-bottom: 1px solid #ccc;
    }
    
   
    input::placeholder{
        font-size: 15px;
    }
    form{
        position: absolute;
        top: 3rem;
        left: 2.5rem;
    }
</style>
<body>
<div id="background"></div>
<form method="POST" enctype="multipart/form-data">

    <p style="color: rgba(206,176,255,0.58)">{{ signup_error }}</p>
    <input id="id_username" placeholder="User Name" type="text" name="username" maxlength="100" required>
    <br/>
    <input id="id_email" placeholder="Email Address" type="text" name="email" maxlength="100" required>
    <br/>
    <input id="id_password" placeholder="Password" type="password" name="password" maxlength="100" required>
    <br/>
    <input id="id_confirmed_password" placeholder="Confirmed Password" type="password" name="confirmed_password" maxlength="100" required>
    <br/>
    <button type="submit">Sign up</button>
</form>

</body>
</html>